= Jenkins workshop masters provisionning

Workshop machines are provisioned using Terraform and Ansible on DigitalOcean cloud.

== Prerequisites

* ansible and terraform installed locally

== Machines creation

.Display terraform execution plan to provision X machines :
[source,bash]
----
$> make plan n=X
----

.Trigger provisionning of X machines :
[source,bash]
----
$> make provision n=X
----

This action will create (or update) X new machines on DigitalOcean cloud accordingly to configuration specified into `jenkins.tf` file.
Then, a provisionning with Ansible `playbook.yml` file is triggered on all created/updates machines.

CAUTION: this action is strictly idempotent. It means that if you start with "make provision n=5" and then execute "make provision n=4", the fifth machine will be directly deleted by terraform !!
To be sure, first run "make plan n = X" and read carefully what are Terraform's plans before a "make provision" action.

== What's the username/password of my instance ?

By default, Jenkins master are provisioned with :

* login = jenkins-${counter}
* password = ${digitalocean_droplet_id}

.You can display all ip/login/password provisioned with Terraform using the following command :
[source,bash]
----
$> make infos
----

== Display Jenkins logs of a target machine

.Assuming you have direct access to target machine (ssh key pushed), you can execute the following command :
[source,bash]
----
$> make logs jenkins-2
----

== Connect to a target machine

.Assuming you have direct access to target machine (ssh key pushed), you can execute the following command :
[source,bash]
----
$> make go jenkins-10
----

